"""
Shared helpers for generating/updating the weekly capital-raise one-pagers
and 00_summary.docx.

Deliberately avoids python-docx's by-name style lookup (doc.styles["Heading 2"],
table.style = "Table Grid", etc.) -- python-docx's BabelFish layer translates
UI names like "Heading 2" to the lowercase internal form "heading 2" before
looking them up via an exact-match XPath on w:name/@w:val. Every docx these
routines have generated so far (docx-js and python-docx alike) writes
w:name w:val="Heading 2" (capitalized, matching the *display* name, not
python-docx's expected internal one), so any by-name lookup raises
KeyError("no style with name ...") even though the style is right there and
even though reading it back (paragraph.style.name) works fine. This hit every
batch in the August 2026 catch-up run. Fix: never look up or assign styles by
name -- apply visual formatting (color/size/bold) directly on runs, and set
table borders by writing tblBorders XML directly. This makes documents
generated by this module immune to the bug regardless of what any given
docx's styles.xml does or doesn't define.
"""
from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

HEADING_BLUE = RGBColor(0x2E, 0x74, 0xB5)
GRAY = RGBColor(0x44, 0x44, 0x44)
US_LETTER_SECTPR_MARGIN = Pt(54)  # ~0.75in via Pt is approximate; docx defaults are fine to leave alone


def heading1(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(16)
    r.font.color.rgb = HEADING_BLUE
    p.paragraph_format.space_before = Pt(14)
    p.paragraph_format.space_after = Pt(6)
    return p


def heading2(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(13)
    r.font.color.rgb = HEADING_BLUE
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after = Pt(4)
    return p


def body(doc, text, italic=False, size=11, color=None):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(size)
    r.italic = italic
    if color is not None:
        r.font.color.rgb = color
    return p


def add_borders(table, sz=4, color="auto"):
    """Apply single-line borders to every cell, matching the visual look of
    Word's built-in 'Table Grid' style, without going through the broken
    by-name style lookup. tblBorders must be inserted directly after tblW
    (and before tblLook) per the CT_TblPrBase schema's declared child order --
    appending it at the end of tblPr fails OOXML validation."""
    tbl = table._tbl
    tblPr = tbl.tblPr
    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "single")
        el.set(qn("w:sz"), str(sz))
        el.set(qn("w:color"), color)
        borders.append(el)
    tblW = tblPr.find(qn("w:tblW"))
    if tblW is not None:
        tblW.addnext(borders)
    else:
        tblPr.insert(0, borders)


def shaded_header_row(table, header_texts, fill="1F3864"):
    """First row of a table: white bold text on a dark-blue fill, matching
    the existing Keep-table header look."""
    row = table.rows[0]
    for cell, text in zip(row.cells, header_texts):
        cell.text = ""
        p = cell.paragraphs[0]
        r = p.add_run(text)
        r.bold = True
        r.font.size = Pt(9)
        r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        tcPr = cell._tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"), fill)
        tcPr.append(shd)


def data_row(table, values, size=8.5):
    row = table.add_row()
    for cell, text in zip(row.cells, values):
        cell.text = ""
        p = cell.paragraphs[0]
        r = p.add_run(str(text))
        r.font.size = Pt(size)
    return row


ONE_PAGER_SECTIONS = [
    ("Thesis", "thesis"),
    ("Use of Proceeds", "use_of_proceeds"),
    ("Timing", "timing"),
    ("Why Raise Now", "why_raise_now"),
    ("Risks to the Pitch", "risks"),
]


def create_one_pager(data, output_path):
    """data keys (all strings unless noted):
      ticker, company_name, sector_industry, market_cap, raise_size,
      pct_market_cap, urgency, thesis, use_of_proceeds, timing,
      why_raise_now, risks
      optional: summary_note (extra italic note under the Summary table,
        e.g. a sizing-cap disclosure)
    """
    doc = Document()

    p = doc.add_paragraph()
    r = p.add_run(f"{data['ticker']} — {data['company_name']}")
    r.bold = True
    r.font.size = Pt(16)

    p = doc.add_paragraph()
    r = p.add_run(data["sector_industry"])
    r.italic = True
    r.font.size = Pt(11)
    r.font.color.rgb = GRAY

    p = doc.add_paragraph()
    r = p.add_run("Current Market Cap:  ")
    r.bold = True
    r.font.size = Pt(11)
    r2 = p.add_run(data["market_cap"])
    r2.font.size = Pt(11)

    p = doc.add_paragraph()
    r = p.add_run("Proposed Raise Size:  ")
    r.bold = True
    r.font.size = Pt(11)
    r2 = p.add_run(f"{data['raise_size']} ({data['pct_market_cap']} of market cap)")
    r2.font.size = Pt(11)

    for title, key in ONE_PAGER_SECTIONS:
        heading2(doc, title)
        body(doc, data[key])

    heading2(doc, "Summary")
    t = doc.add_table(rows=1, cols=5)
    shaded_header_row(t, ["Ticker", "Market Cap", "Raise Size", "% of Market Cap", "Urgency"])
    data_row(t, [data["ticker"], data["market_cap"], data["raise_size"], data["pct_market_cap"], data["urgency"]])
    add_borders(t)

    if data.get("summary_note"):
        body(doc, f"Note: {data['summary_note']}", italic=True, size=9, color=GRAY)

    doc.save(output_path)
    return output_path
